services:
  - type: web
    name: 傾青-fb-generator
    runtime: python
    buildCommand: apt-get install -y fonts-noto-cjk fonts-wqy-zenhei || true && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
